### ISSUE TITLE
Lein run fails on fresh clone

### ISSUE THREAD

**Issue by neverfox** [qiuxiafei/zk-web#24]
It doesn't look like this project is maintained anymore, but this is what I got from a fresh clone `lein run`:
```
Exception in thread "main" java.lang.IllegalArgumentException: Don't know how to create ISeq from: clojure.lang.Symbol
	at clojure.lang.RT.seqFrom(RT.java:494)
	at clojure.lang.RT.seq(RT.java:475)
	at clojure.lang.RT.first(RT.java:567)
	at clojure.core$first.invoke(core.clj:55)
	at clojure.core$defmacro$add_implicit_args__3765.invoke(core.clj:433)
	at clojure.core$defmacro$add_args__3767.invoke(core.clj:441)
	at clojure.core$defmacro.doInvoke(core.clj:442)
	at clojure.lang.RestFn.invoke(RestFn.java:644)
	at clojure.lang.Var.invoke(Var.java:445)
	at clojure.lang.AFn.applyToHelper(AFn.java:202)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6366)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6427)
	at clojure.lang.Compiler.eval(Compiler.java:6495)
	at clojure.lang.Compiler.load(Compiler.java:6952)
	at clojure.lang.RT.loadResourceScript(RT.java:359)
	at clojure.lang.RT.loadResourceScript(RT.java:350)
	at clojure.lang.RT.load(RT.java:429)
	at clojure.lang.RT.load(RT.java:400)
	at clojure.core$load$fn__4890.invoke(core.clj:5415)
	at clojure.core$load.doInvoke(core.clj:5414)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5227)
	at clojure.core$load_lib.doInvoke(core.clj:5264)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.core$load_libs.doInvoke(core.clj:5298)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:603)
	at clojure.core$require.doInvoke(core.clj:5381)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at vinyasa.inject$inject_row_entry.invoke(inject.clj:56)
	at vinyasa.inject$inject_row$fn__584.invoke(inject.clj:82)
	at clojure.core$map$fn__4087.invoke(core.clj:2432)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$apply.invoke(core.clj:601)
	at clojure.core$mapcat.doInvoke(core.clj:2461)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at vinyasa.inject$inject_row.invoke(inject.clj:82)
	at clojure.core$map$fn__4087.invoke(core.clj:2432)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:473)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$apply.invoke(core.clj:601)
	at clojure.core$mapcat.doInvoke(core.clj:2461)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at vinyasa.inject$in.doInvoke(inject.clj:95)
	at clojure.lang.RestFn.invoke(RestFn.java:826)
	at clojure.lang.Var.invoke(Var.java:455)
	at clojure.lang.AFn.applyToHelper(AFn.java:223)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6366)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6427)
	at clojure.lang.Compiler.eval(Compiler.java:6495)
	at clojure.lang.Compiler.eval(Compiler.java:6500)
	at clojure.lang.Compiler.load(Compiler.java:6952)
	at clojure.lang.Compiler.loadFile(Compiler.java:6912)
	at clojure.main$load_script.invoke(main.clj:283)
	at clojure.main$init_opt.invoke(main.clj:288)
	at clojure.main$initialize.invoke(main.clj:316)
	at clojure.main$null_opt.invoke(main.clj:349)
	at clojure.main$main.doInvoke(main.clj:427)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:419)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.Var.applyTo(Var.java:532)
	at clojure.main.main(main.java:37)
```

**Comment by qiuxiafei** [comment]
Sorry for that i actually  failed to maintain the project for a long time. Maybe i am investigating your problem soon.
